[plugin]
id = "com.steamstatusstudio.live"
name = "Steam Status Studio Live"
version = "1.1.0"
author = "Steam Status Studio"
description = "自定义你的 Steam 状态。"

[backend]
entry = "src/main.lua"
sources = ["src/main.lua"]

[frontend]
entry = "src/index.tsx"

[compiler]
output_path = "dist/com.steamstatusstudio.live.star"
